const searchTargets = [
  "Honolulu, Ha",
  "Horseshoe bend in Arizona",
  "Hostan",
  "Hot Springs, mn",
  "Hot Springs, SD",
  "hot tub & gambling",
  "Houghton Skatepark, Long Beach",
  "hustaon",
  "Hwy 1, CA",
  "i cant rememmber",
  "I have fun",
  "I have not seen any ads",
  "I heart radio",
  "I love this",
  "Iberostar",
  "Id k",
  "Idah o",
  "Idaho (Yellowstone)",
  "idaho bear world",
  "Idaho Springs,Co",
  "Idaho State",
  "ideo",
  "Idly",
  "idoho",
  "iefin island",
  "Ifk",
  "Ihowa",
  "iIllinoise",
  "illinoes",
  "Indeed",
  "Iphone 8",
  "Iron mission state park",
  "Iserel",
  "Island of adventure",
  "Italie",
  "Italu",
  "italya",
  "Jackpot, NV",
  "Jackson Ville",
  "Jackson,",
  "Jan",
  "Janesville, Wisconsin",
  "Japanese garden in renton",
  "Jedda",
  "Jermany",
  "Jeruselem",
  "jet port",
  "jiminy peak resort",
  "joban",
  "John Day Oregon",
  "Joplin Missouri",
  "Joseph, Oregon",
  "joshua park",
  "Joyce",
  "Ju",
  "Kadoka, SD",
  "Kailua Kona, Hawaii",
  "Kalahari Resorts",
  "Kalaloch WA",
  "Kalispell, Mo",
  "Kamloop resort",
  "Kansas city , missouri ,usa",
  "Katchikan, AK",
  "Kauai hi",
  "Kauai in Hawaiian islands",
  "kauia",
  "Kellogg",
  "Keneetah resort or",
  "KENNEBUNKPORT, ME",
  "Kent, CT",
  "Ketchican ak",
  "Kihei, Hawaii",
  "Killingtin",
  "Kin",
  "Kinder la",
  "Kinder,LA",
  "kingdom",
  "Kissimmee florida",
  "Kitsap",
  "Kitsap County",
  "kjgkuj",
  "Knoxville.TN",
  "Kodiak",
  "Kolob canyon",
  "Kona, Ha",
  "Korea town Los angeles",
  "Kuaii",
  "KY Horse Park",
  "L is Angela's, ca",
  "La Jolla Coves",
  "LA/ Disneyland",
  "Lacombe",
  "Laconor",
  "Lafayette,LA",
  "Lagoon Amusement Park, Farmington",
  "Lagrange Oregon",
  "Laje Tahoe",
  "lak tahoe",
  "Lake Arrowhead, CA",
  "Lake Charles Louisiana",
  "Lake Chitauqua",
  "Lake cowichan",
  "lake meaxde nevada",
  "Lake Oochacobbi",
  "Lake pend orielle",
  "Lake Powell, Arizona",
  "Lake Powell, NV",
  "lake tahoek, nevada",
  "Lake Travis",
  "Lakes in Michigan",
  "Lakeview",
  "Lakewood castle",
  "Lame",
  "Langley, WA",
  "Lansing,MI",
  "Laramie, Wyoming",
  "Las Cabos",
  "Las Cruces. NM",
  "las florida",
  "Las vef",
  "Las vegas , nevada usa",
  "Las vegas ,nevada , usa",
  "Las Vegas Rodeo",
  "Las Vegas show",
  "Las Vegas Strip, Las Vegas",
  "Las Vegas. NV",
  "Las Vegus Nevada",
  "Laughlin  Nevada",
  "Lauglin, NV",
  "Laurel highlands",
  "Lava hot springs,  Idaho",
  "Lava Hot Springs, Idaho",
  "lavenworth",
  "Lawrence",
  "Lawton oklahoma",
  "Layton, UT",
  "Leavenworth, Wa.",
  "Lee's Summit, Missouri",
  "legrand or",
  "Lehmans cave nevada",
  "Leslie Gulch",
  "Let peninsula",
  "Levant",
  "Levensworth",
  "Levenworth wa",
  "Levinworth",
  "lewis ginter botanical garden",
  "Lewistown",
  "Lexington, wa",
  "Libby Montana",
  "Libby, MT",
  "Liberty lake",
  "Liberty lake park",
  "lifetime",
  "Like place market",
  "Limon Costa Rica",
  "Lincold city",
  "Little Niagara falls",
  "livingston",
  "Livingston, MT",
  "livrbol",
  "Logam, Oho",
  "Lolo Montana",
  "London, U.K.",
  "Londoner",
  "Long beach,  wa",
  "Longboat Key, FL",
  "Lopez Island, WA",
  "Los vangas",
  "losangelse",
  "Low Angeles/San Diego/Ft Worth",
  "Lowell Observatory",
  "LSE",
  "Lucky Labrador Brewing Company",
  "Lusk Wyoming",
  "Lyden",
  "macall",
  "Macao",
  "Macheny mannor",
  "Machu Picchu",
  "mackay idaho",
  "Maddison Square Garden",
  "madred",
  "Mahatthan",
  "Makinec island",
  "Malad",
  "Malad idaho",
  "malaysian",
  "Maldives's",
  "malisia",
  "Malta montana",
  "Manila",
  "Manito",
  "Manitoba Canada",
  "Manitowoc wiscoin",
  "Mantcher",
  "Manzanita Beach",
  "Maple falls",
  "Mariposa County, CA",
  "markers",
  "Maryville,ca",
  "masachuchest",
  "Maskete",
  "mason city IA",
  "Mason, Texas",
  "Massatuchets",
  "Mather Point",
  "Mauch  Chunk",
  "Maui HI - Facebook advertisement",
  "Maupin Oregon",
  "Maverik",
  "maxprime",
  "Mazatland",
  "McCord Afb",
  "Meat",
  "Mendocino California",
  "Menneapolis",
  "Menroe",
  "Mesa Falls",
  "Mexican cruise",
  "Mexico, Cruses & Resorts",
  "Mexico,puerta Vallarta",
  "Mexixo",
  "Mexoco",
  "miagra",
  "miami see beach",
  "Michigaan",
  "Michigan U P",
  "Midway, ut",
  "Midway, Utah",
  "milano",
  "Mililani hawaii",
  "minessotga",
  "Minot, ND",
  "Minsoda",
  "Mintana",
  "Miramar Beach",
  "Missapi",
  "Missipi",
  "missoila montana",
  "Missoula, Momtana",
  "Missury",
  "misupissi",
  "mkyr",
  "MLASIA",
  "MN.",
  "Moab, Utah (arches / canyonlands)",
  "moning side flight park",
  "Monroe, Wa",
  "Montana/Glacier",
  "Montana’s Flathead Valley",
  "Montpelier, Idaho",
  "Montreal CA",
  "montw",
  "Montwna",
  "Moore, NC",
  "Morrison colorado",
  "Most. Most.",
  "Mother cabrini",
  "Moumt Everest",
  "Mount baker forest",
  "Mount Pleasant",
  "Mount Rainier Natl Park",
  "Mount Rushmore, SoDak",
  "Mount saint Helen's",
  "mount shasta city california",
  "Mount St Helen's",
  "Mountain rainier",
  "mountain s",
  "Mountain trail",
  "mountain view grand resorts",
  "Mountains NC",
  "mountains smokies",
  "mountsin top inn",
  "Movie Theater",
  "Mr spokane",
  "Mr. Raineer",
  "Mt evans",
  "Mt hood or",
  "Mt Morris pa",
  "mt roushmore",
  "Mt St Hekens",
  "Mt Vernon, ia",
  "Mt. Rushmoore",
  "Mt. St. Helen",
  "Mt.Rainier National Park",
  "Muckelshoot casino",
  "Multinoma",
  "Murrat",
  "mvok",
  "mwv",
  "mwvmw",
  "My rainer",
  "My Rushmoore",
  "My. Adams",
  "My. Rainer",
  "My. Ranier",
  "myrtle brach",
  "N. Y",
  "NA",
  "Nampo, ID",
  "Napili",
  "Naples  Florida",
  "National Park of the Great Basin",
  "Natural history museum in price Utah",
  "Natural scenic viewing",
  "Naturlall breidge",
  "Nayagra falls",
  "Nayak",
  "NC ashevile",
  "Nebraska Prairie",
  "New  Mexico",
  "New .Mexico",
  "new carolina",
  "New Delhi",
  "New Guinea",
  "New Hampshire Lakes Region",
  "new hapshire",
  "New hempsher",
  "new hempshire",
  "new jersi",
  "New Mexico petrified forest",
  "New mexocp",
  "New Orleands LA",
  "New Orleans ls",
  "New port news Va",
  "New port, Wa",
  "New Salem Village",
  "new tourk",
  "New year",
  "New yoek",
  "New York Albany",
  "New York Miami",
  "New York the whole state",
  "New York time square",
  "New York/Hamptons",
  "New youl",
  "newbridge",
  "Newfoundland/Labrador",
  "newport washington",
  "newyork beach",
  "newyork ny",
  "nexflix",
  "neywork",
  "Niagara Falls, Ontario, Canada",
  "Niegara",
  "Nigagra Falls",
  "niokne",
  "Nisqually falls",
  "ñldsfñsdf",
  "nnne",
  "No Carolina",
  "none i",
  "none within the US",
  "noneq",
  "NONME",
  "nonwe",
  "Nortern California",
  "North Carolina smoky mountains",
  "North Central Washinb]gton",
  "North Pole, AK",
  "North West/Seattle",
  "Northbend",
  "Northeast Seaboard",
  "northen rockiesmaggie valey",
  "Northern Caliafornia",
  "Northern California king valley",
  "Northern Muchigan",
  "Northern.",
  "Northwest Montana",
  "Northwest track",
  "Norwegian Cruiseline",
  "Nosara, Costa Rica",
  "nothern virginia, applacian trail",
  "Nova Socia",
  "NPONE",
  "npose",
  "Oahoma",
  "Oakland Oregon",
  "Oatman",
  "ocean city,md.",
  "ocean island",
  "ocean shores ,wa",
  "Oceanshore",
  "oefm",
  "Of any besides",
  "Ogden, Utah",
  "Ohayo",
  "Okanogan County",
  "Okay casino",
  "Old Rag",
  "Old Trafford",
  "Olde forge New York",
  "Oldest town in America",
  "Olympia wz",
  "Olympic Forrest Washington",
  "Olympic Game Farm",
  "Olympic National Forrest",
  "Olympic Peninsula, WA",
  "Olympic Peninsyla",
  "Olympic pensiula",
  "Olympic Range",
  "Olympics WA",
  "O'Neill Nebraska",
  "Oneonta, Oregon",
  "Only to Mexico",
  "Oregon coast  (lighthouses",
  "Oregon Nat'l Parks",
  "Oregon out n about",
  "Oriophino",
  "Orlando/Disneyworld",
  "orlandon",
  "Orofino",
  "Orogen",
  "Ourray",
  "Outerbanks beach",
  "Overland Park, KS",
  "Owatc",
  "Oxford",
  "Oxford, NC",
  "P.E.I.",
  "Pa wilds",
  "Pacfic Northwest",
  "Pacific Oregon Coast",
  "Pacificocean",
  "Painted dessert az",
  "Paiute Trail, Utah",
  "palm sprins",
  "Palmyra, ny",
  "Paraguay",
  "parasailing",
  "Parck city",
  "Paris France. The sparkling City",
  "Paris Museum",
  "Park Citry, Ut",
  "Park City, Ut.",
  "park city,utah",
  "Parque Nacional Zion, Utah",
  "Pcocnos, PA",
  "Peace garden",
  "Peace river. AB  Canada",
  "Peddlers village",
  "Penticton",
  "penysilvia",
  "peris",
  "Pheonex",
  "Philadelhia",
  "Phillipsburg Montana",
  "Phinox",
  "Phionxe",
  "Phoenix area",
  "pig beach",
  "Pike Place",
  "Pike's Place, Seattle",
  "Pisa italy",
  "pitsburtg",
  "Pittsburgh, Pennsylvania",
  "Pittsfield",
  "PITTSFIELD, MA",
  "Playa delCarmen",
  "playboy",
  "pmv",
  "pocantico hills",
  "Pocono Mountains, Pa.",
  "Pocons",
  "POERLAND",
  "Poetland",
  "poetland oregan",
  "Point defiance",
  "Point defiance zoo and aquarium",
  "Point no point",
  "Poipu, Kauai, HI",
  "Port O'Connor,TX",
  "Port orchard Washington",
  "portlamd",
  "Portland  maine",
  "Potholes State Park, WA",
  "Priest river idaho",
  "Priest Rock",
  "Princess cruise ships",
  "Publoo",
  "puebla mexico",
  "Pueblos, co",
  "Puerto Rick",
  "puetro rico",
  "Pugeot Sound",
  "Puget Sound Seattle Washington",
  "Punta del Este, Uruguay",
  "Puru",
  "Queb3c",
  "Quilcene",
  "Quinns hot springs montana",
  "Radido",
  "Radio 91.7",
  "Rainer National Park",
  "raly",
  "rangely co",
  "RANGELY, MAINE",
  "ranger",
  "Rapid  City",
  "Rattlesnake mountain",
  "reatin",
  "Red deer",
  "Red Rock Canyon, NV",
  "Red Rocks Amphitheater",
  "Red rocks Colorado",
  "Red wood forest, California",
  "Redfeather Lakes",
  "Redlands, CA",
  "Redmond oregon",
  "Redmond, utah",
  "Redwood National  Park",
  "Redwood natl forest",
  "Redwood parks",
  "reefrgt",
  "regw4",
  "Remenber",
  "Reno , nevada , usa",
  "Reptile Gardens",
  "retret",
  "Revelstoke",
  "Rewood National Park, Cali",
  "rgtert",
  "rgthyj",
  "Rhinebeck",
  "Rhinelander WI",
  "rhode isalnd",
  "Rice terrace fields of longsheng",
  "Richfield, utah",
  "Rife lake",
  "Riggins, ID",
  "Riodoso, NM",
  "River cruise Mississippi",
  "River lodge idaho",
  "Riverside State Park",
  "rizona",
  "Rock Away Oregon",
  "Rock creek campgrounds",
  "Rock springs wyoming",
  "Rockport,TX",
  "Rocky gap md",
  "Rocky Mountain National Park/Estes Park, CO",
  "Rocky Mountanin National Park",
  "Rocky Mountian National Forrest",
  "Rocky Mtn",
  "Rocky Mtn National Park, Colo",
  "rode  island",
  "rohobeth beach,de.",
  "Roman Nose, OK",
  "Roosevelt",
  "Roosevelt, UT",
  "Rosario resort Washington",
  "roseberg, oregon",
  "Roseburg",
  "Round Valley resevoir",
  "Royal Caribbean  cruise",
  "rrrrrrry",
  "rrtyr",
  "rtrh",
  "rupert",
  "Rusdia",
  "Rutland, VT",
  "Sadly lake city",
  "SAF",
  "safg",
  "Saguaro National Minument",
  "Salida,Co",
  "Salina, UT",
  "Salina, utah",
  "Salmon Id",
  "Salmon Le Sac WA",
  "Salt lake  city",
  "Salt lake theatre",
  "SALT LIKE CITY",
  "Salt palace",
  "sampa",
  "Samsung 8",
  "Samsung galaxy note 8",
  "San Deigo CA",
  "san diage",
  "San diego , california ,usa",
  "San Diego, Californis",
  "San Fran Cisco",
  "San Francion",
  "San francisco , california ,usa",
  "San Francisco’s",
  "San Fransisco Redwoods",
  "San jose de california",
  "San Juan Iands",
  "San Juan Isands",
  "San Juan’s",
  "san juans",
  "San Luis Valley",
  "San sana, tx",
  "San simion",
  "Sand hollow,  Utah",
  "Sand jaun islands",
  "Sand point idaho",
  "sandal islands",
  "Sandals beach resort",
  "Sandals Resorts Caribbean",
  "Sandals. Resorts",
  "sandalwood",
  "sanders",
  "Sands casino",
  "Sandy UT",
  "Sanibel Florida",
  "Santa monica , california ,usa",
  "Santa Rosa, California",
  "SANTANA",
  "Sante Fa, NM",
  "Sante Fe,  NM",
  "Sao Paulo",
  "Sarasoto FL",
  "Sask,Canada",
  "sasketchwan",
  "Sauk Mt. Washington",
  "Sault Ste Marie, michigan",
  "sceenery",
  "Scotland promo",
  "Scottish Highlands",
  "sea bech",
  "Sea Side Oregon",
  "Sea World Texas",
  "Searrle",
  "seattel washington",
  "Seattle ferris wheel",
  "Seattle National Park",
  "Seattle Wa - Television advertisement",
  "seattle, ea",
  "Seattle/Portland",
  "Secret resorts",
  "see above",
  "Seeley lake",
  "Sequin State Park",
  "SEQUOIA REDWOODS",
  "Seven peaks",
  "Seven springs pa",
  "Sevierville,  TN",
  "Shawarma",
  "Shawnee ski",
  "Shenandoah mountain",
  "Shenondoah national park",
  "Ship rock New Mexico",
  "Shipshewana, Indiana",
  "Showlo,ariz",
  "Silverthorne",
  "Silverwood six flags",
  "Simons National Park",
  "Sitka ak",
  "Six flags Orlando",
  "Skagit county, wa",
  "Ski town",
  "skiing in Montana",
  "Sleepy Hallow",
  "Small Water Museum in Pocatello, ID",
  "Smiley mountains",
  "Smith Tower",
  "smithonian",
  "Smokey Mountains Tennesse",
  "Smoky mountains, NC",
  "Smoky mts NP",
  "Snoqualmie pass casino",
  "Snoqualmie, WA",
  "Snow Canyon State Park",
  "Snow shoeing in Colorado mountains",
  "Snowbird resort",
  "Snowbird ski resort",
  "Snowboarding in Washington",
  "snowflake mountain resort",
  "Snowqualmie casino",
  "Snows summit",
  "snowshoe, CO",
  "Snowy Range",
  "Snwibv",
  "Soda Spring, Idaho",
  "soda springs",
  "SOESRA",
  "Somewhere in Mt",
  "Sonoma County CA",
  "Sonora, CA.",
  "Soouth Dakota",
  "south carolana",
  "South Catolina",
  "south dkota",
  "South Doaktona",
  "South East ohio",
  "South tx",
  "south west usa",
  "Southwest Montana",
  "Space middle",
  "Space nidde",
  "Sparks NV",
  "Sparta BC",
  "Sparta, North Carolina",
  "Spave center",
  "Spending",
  "Split mountain",
  "Spokane,Washington",
  "spopods",
  "Sportung events",
  "Springfield, Ohio",
  "Springville/Zion National Park, UT",
  "squamish, BC",
  "Squim",
  "srft",
  "st augusine",
  "St Helens national park",
  "st lawrence county, ny",
  "St Louis Park MN",
  "St Luis Missouri",
  "St saint marie",
  "St, John USVI",
  "St. Augustine, Fl.",
  "St. George and Tuacahn Performances",
  "St. George golf",
  "St. Helena, CA.",
  "St. Helens, OR",
  "St. Mary.GA",
  "St. Michele winery",
  "St. Petersburg florida",
  "St.. Paul, MN",
  "St.Kits",
  "STATE COLLEGE, PA",
  "State of Hawaii",
  "state of nevada",
  "State of Wyoming",
  "Statue of Liberty WebsiteDirections",
  "Steam Boat",
  "Steam Boat Springs, Co",
  "Steamboat rock state park",
  "Steamboat Springs. CO",
  "Stergis, SD",
  "Steve Pass",
  "Stone age",
  "Stone Mtn Park",
  "Stonewall, Colo",
  "String Lakes",
  "Stub Stewart",
  "Suiox Falls",
  "Sul duc",
  "Sun Fransisco",
  "Sun peaks",
  "Sun Vally",
  "Sundance ski resort",
  "sunfransisco",
  "Sunset Beach Resorts",
  "SunValley Idaho",
  "SunValley, Idaho",
  "Swahili",
  "Swedan",
  "Sweetwater, WY",
  "swimming pool",
  "SXSW",
  "Tabet",
  "Tacoma glass museum",
  "Tahoe, California/Nevada",
  "Take trip",
  "Take walk",
  "Tamerac",
  "tantalus",
  "Targhee ski resort",
  "Tavel",
  "teens",
  "Telleride",
  "Temple Square, SLC",
  "Tenasket",
  "Tennessee’",
  "Tensleep, WY",
  "Tenton",
  "texas houston",
  "Texas/Alamo/San Antonio",
  "Texss",
  "That's all I",
  "The Adirondacks, New York",
  "The Alps",
  "The Broadmore",
  "The Capitol",
  "The Columbia George",
  "The Everglades in flirida",
  "the faces",
  "The Gorge, Wa",
  "The gorge,wa",
  "The Hawaiian island of Maui",
  "The Nantucket Hotel & Resort",
  "the Seychelles",
  "The Ski Week",
  "the smokey mountain states",
  "the star's in side walks",
  "the warner studies",
  "The Woodlands",
  "The Yacht Week",
  "The zoo",
  "Theatres",
  "Thomas and Friends",
  "Thompson falls",
  "Tiajuana",
  "Tillicum native American tour, the birth of Chief Seattle, WA state",
  "Time Square,NY",
  "Tired",
  "Tonopah, NV",
  "Torfino",
  "Tower of leaning piazza",
  "Traffic",
  "Transverse City Michigan",
  "travel to atlanta",
  "travelgo",
  "Travellers",
  "Trees of Mystery",
  "Triple play",
  "trobago",
  "Trout creek montana",
  "Troutdale, Oregon",
  "trtr",
  "Tuacahn",
  "Tukwila",
  "tulalip casino, WA",
  "Tulalip Resort Casino",
  "tulula gorge",
  "Turks and cacous",
  "Turks caicos",
  "TURKSANDCURCOS",
  "Twain",
  "Twisp",
  "tx towns",
  "Ubc",
  "Uganda",
  "ugiuh",
  "ugiukj",
  "ugouhl",
  "Uintahs",
  "Understand",
  "Union Station, Washington, D.C.",
  "Union, WA",
  "Unita Mountains",
  "United Arab Emirates",
  "Universal Studios FL - Television advertisement",
  "Universal studios Harry Potter",
  "univision",
  "Up north in Michigan",
  "Update New York",
  "Upper Mi",
  "Upper Penninsula MI",
  "US Parks",
  "Utah (mount Carmel area)",
  "Utah mines",
  "Utah,",
  "Utah/Arches/Zion",
  "utopia",
  "Utube",
  "utyg",
  "v 6",
  "VA.",
  "Vail,  CO",
  "Valle Skagit, Washington",
  "valrimnoew",
  "Vancouver b.c",
  "Vancouver or Victoria, BC",
  "Vancouver, B. C.",
  "vanity fair",
  "Vantage",
  "Vanz",
  "varginia",
  "various",
  "vbb",
  "vcbvn",
  "Vegas....yuck",
  "Vermont in the fall",
  "Victoria Canada",
  "vinice",
  "virgaina city",
  "Virginia Beach, Va.",
  "virginya",
  "VISIT BALTIMORE",
  "Visit Boston, Massachusetts",
  "VISIT BRUSSELS",
  "Visit Park City",
  "Visit Portland, Oregon",
  "Visit Vermont",
  "Visiting national parks",
  "vko",
  "vmw",
  "volcanoes national park",
  "vouyager national park",
  "VRBO",
  "w. virginia",
  "WA  state",
  "wachintong",
  "walker",
  "Wallace id",
  "Wallowa Lake, wa",
  "Walls walla",
  "Walt Disney, CA",
  "Walt Disny",
  "Walt Disny World",
  "Wanatchee",
  "Wasaga beach",
  "Washibgton , DC",
  "washingot dc",
  "washingotn DC",
  "Washington coastline",
  "Washington D.C. Zoo",
  "Washington State Peninsula",
  "Washington, D. C.",
  "Washjngton",
  "Washongton dc",
  "wasshington coast",
  "Water rafting and camping",
  "Watertown sd",
  "Waterville",
  "Wendorver Nevada",
  "wequassett resort",
  "West coast beaches",
  "West Virginia rafting",
  "Western Oregon",
  "Western Wasington",
  "whasinton",
  "Wheatland, wy",
  "Whidbey",
  "Whidby island",
  "whiite mountains",
  "Whistler B.C.",
  "whistler, british columbia",
  "Whistler, Canada",
  "Whitaker Point",
  "White horse canada",
  "White water national forest",
  "Whitefisg",
  "Wild horses Oregon",
  "wildcat hills",
  "Wildlife Zoo",
  "Wildwaves",
  "wiliamsburg",
  "Willamit valley",
  "Williston, ND",
  "Willow Creek",
  "wine tours",
  "Winnetu Oceanside Resort",
  "Winter Olympics",
  "Winter Park, Colorado",
  "winthrop, washington",
  "Wisconic",
  "Wisconic Musum",
  "Wiscosin",
  "Wiskeytown Lake",
  "Wolfeboro",
  "Wonderland",
  "woodstock ny",
  "world city",
  "wrtwret",
  "wshinton dc",
  "Wyong",
  "xvcb",
  "Yahatchs",
  "Yamhill",
  "yellow stone ntl park",
  "yellowstne",
  "Yellowstone National Parj",
  "Yellowstone Park, Wyom",
  "yellowstone wyo",
  "Yellowstonr National Park",
  "Yelm,wa",
  "yexas",
  "Yo",
  "yosemitie park",
  "yosetmite",
  "yositite",
  "Yosmity",
  "yountaille",
  "yourk",
  "yryry",
  "Yuba City, CA",
  "Zion  canyon",
  "Zion National Parks",
  "Zion’s",
  "Zion’s Park",
  "Zions National  Park"
];
